---

- name: copy and deploy to dev server
  hosts: web
  become: yes
  tasks:
  - name: copy the jar file to remote server
    copy:
      src: target/*.jar
      dest: /opt/tomcat/webapps
      owner: root
      group: root
      mode: '0644'
      remote_src: yes
  - name: restart the tomcat server
    service:
      name: tomcat
      state: started

