---

- name: copy and deploy to dev server
  hosts: web
  become: yes
  tasks:
  - name: copy the jar file to remote server
    copy:
      src: target/my-app-1.0-SNAPSHOT.jar
      dest: /opt/tomcat/webapps
      mode: '0644'
     
  - name: restart the tomcat server
    service:
      name: tomcat
      state: started

